root = "."
tmp_dir = "tmp-node2"

[build]
cmd = "go build -o ./tmp-node2/genomdb ."
bin = "./tmp-node2/genomdb"
full_bin = "./tmp-node2/genomdb start configs/config-node2.yml"
include_ext = ["go", "yml", "yaml"]
exclude_dir = ["data", "tmp", "tmp-node1", "tmp-node2", "tmp-node3", "vendor", ".git"]
delay = 200
stop_on_error = true

[log]
time = true
