database: "data/node2/node2.db"

server:
  host: "0.0.0.0"
  port: 8002

raft:
  node_id: "node2"
  bind_addr: "0.0.0.0"
  advertise_addr: "node2"
  data_dir: "data/node2"
  peers:
    - "node1:9025"
