database: "data/node3/node3.db"

server:
  host: "0.0.0.0"
  port: 8003

raft:
  node_id: "node3"
  bind_addr: "0.0.0.0"
  advertise_addr: "node3"
  data_dir: "data/node3"
  peers:
    - "node1:9025"
    - "node2:9026"
